apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditseverity-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditSeverityModule  
  template:
    metadata:
      labels:
        app: AuditSeverityModule
    spec:
      containers:
      - name: severitycontainerinst
        image: auditmanagementcreg.azurecr.io/severitycontainerrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: authsvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: auditseveritymodule
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditSeverityModule
